// <auto-generated>
// This code was generated by the OPAL compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Opal.Runtime;

namespace Contracts
{
    public static class ContractsModule
    {
        public static void Main()
        {
            Console.WriteLine("=== OPAL Contracts Demo ===");
            Console.WriteLine("");
            Console.WriteLine("Testing Square(5) - has REQUIRES x >= 0 and ENSURES result >= 0");
            Console.WriteLine("  If precondition fails, throws ArgumentException");
            Console.WriteLine("  If postcondition fails, throws InvalidOperationException");
            Console.WriteLine("");
            Console.WriteLine("Testing Divide(10, 2) - has REQUIRES b != 0 with custom message");
            Console.WriteLine("  Custom message: divisor must not be zero");
            Console.WriteLine("");
            Console.WriteLine("Contracts are enforced at runtime with clear error messages.");
        }

        public static int Square(int x)
        {
            if (!((x >= 0))) throw new ArgumentException("Precondition failed: (x >= 0)");
            int __result__ = default;

            __result__ = (x * x);

            if (!((__result__ >= 0))) throw new InvalidOperationException("Postcondition failed: (__result__ >= 0)");
            return __result__;
        }

        public static int Divide(int a, int b)
        {
            if (!((b != 0))) throw new ArgumentException("divisor must not be zero");
            return (a / b);
        }

    }
}
