// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;

namespace Hello
{
    public static class HelloModule
    {
        public static void Main()
        {
            Console.WriteLine("Hello from Calor E2E Test!");
        }

    }
}
