// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;
using System.Collections.Generic;
using System.Linq;

namespace FizzBuzz
{
    public static class FizzBuzzModule
    {
        public static void Main()
        {
            for (var i = 1; i <= 100; i++)
            {
                if (((i % 15) == 0))
                {
                    Console.WriteLine("FizzBuzz");
                }
                else if (((i % 3) == 0))
                {
                    Console.WriteLine("Fizz");
                }
                else if (((i % 5) == 0))
                {
                    Console.WriteLine("Buzz");
                }
                else
                {
                    Console.WriteLine(i);
                }

            }

        }

    }
}
