// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;

namespace Contracts
{
    public static class ContractsModule
    {
        public static void Main()
        {
            Console.WriteLine("Testing contracts...");
        }

        public static int Square(int x)
        {
            // PROVEN: Precondition always satisfiable: (x >= 0)
            int __result__ = default;

            __result__ = (x * x);

            if (!((__result__ >= 0))) throw new Calor.Runtime.ContractViolationException("Postcondition failed: (__result__ >= 0)", "f002", Calor.Runtime.ContractKind.Ensures, startOffset: 187, length: 16, sourceFile: null, line: 15, column: 3, condition: "(__result__ >= 0)");
            return __result__;
        }

        public static int Divide(int a, int b)
        {
            // PROVEN: Precondition always satisfiable: (b != 0)
            return (a / b);
        }

    }
}
