// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;
using System.Collections.Generic;
using System.Linq;

namespace PatternDemo
{
    public static class PatternDemoModule
    {
        public static string GetGrade(int score)
        {
            return score switch { >= 90 => "A", >= 80 => "B", >= 70 => "C", >= 60 => "D", _ => "F" };
        }

        public static string GetHttpStatus(int code)
        {
            return code switch { 200 => "OK", 404 => "Not Found", 500 => "Server Error", _ => "Unknown" };
        }

        public static string Describe(int x)
        {
            return x switch { var n when (n > 100) => "large", var n when (n < 0) => "negative", 0 => "zero", _ => "normal" };
        }

    }
}
