// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;
using System.Collections.Generic;
using System.Text;

namespace Transliterator
{
    public class TransliteratorBase
    {
        public abstract string Name { get; set; }

    }

    public class CyrillicToLatin : TransliteratorBase
    {
        private string _mappings;
        public override string Name { get; set; }

        public CyrillicToLatin(string name)
        {
            this._mappings = name;
        }

        public string Transliterate(string input)
        {
            var dict = new Dictionary<char, string>();
            char[] buf = new char[256];
            var sb = new StringBuilder();
            ConsoleKeyInfo keyPressed = Console.ReadKey();
            for (var i = 0; i <= input.Length; i++)
            {
                char ch = input[i];
                if ((ch == 'Y'))
                {
                    sb.Append("Y");
                }
                else
                {
                    sb.Append(ch);
                }

            }

            Console.WriteLine(new StringBuilder(), new StringBuilder());
            return sb.ToString();
        }

    }

}
