// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Calor.Runtime;

namespace Collections
{
    public static class CollectionsModule
    {
        public static void Main()
        {
            Console.WriteLine("=== Calor Collections Demo ===");
            Console.WriteLine("");
            Console.WriteLine("--- List Operations ---");
            List<int> numbers = new List<int>() { 10, 20, 30 };
            Console.WriteLine("Created list: [10, 20, 30]");
            numbers.Add(40);
            Console.WriteLine("After push(40): [10, 20, 30, 40]");
            numbers.Insert(0, 5);
            Console.WriteLine("After insert(0, 5): [5, 10, 20, 30, 40]");
            numbers[2] = 25;
            Console.WriteLine("After setIndex(2, 25): [5, 10, 25, 30, 40]");
            Console.WriteLine("");
            Console.WriteLine("--- Dictionary Operations ---");
            Dictionary<string, int> scores = new Dictionary<string, int>() { { "Alice", 95 }, { "Bob", 87 } };
            Console.WriteLine("Created dict: {Alice: 95, Bob: 87}");
            scores["Charlie"] = 92;
            Console.WriteLine("After put(Charlie, 92): {Alice: 95, Bob: 87, Charlie: 92}");
            scores["Bob"] = 90;
            Console.WriteLine("After put(Bob, 90): {Alice: 95, Bob: 90, Charlie: 92}");
            Console.WriteLine("");
            Console.WriteLine("--- HashSet Operations ---");
            HashSet<string> tags = new HashSet<string>() { "important", "urgent" };
            Console.WriteLine("Created set: {important, urgent}");
            tags.Add("review");
            Console.WriteLine("After add(review): {important, urgent, review}");
            tags.Remove("urgent");
            Console.WriteLine("After remove(urgent): {important, review}");
            Console.WriteLine("");
            Console.WriteLine("=== Demo Complete ===");
        }

    }
}
