// <auto-generated>
// This code was generated by the OPAL compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Opal.Runtime;

namespace TypeSystem
{
    public static class TypeSystemModule
    {
        public static void Main()
        {
            Console.WriteLine("=== OPAL Type System Demo ===");
            Console.WriteLine("");
            Console.WriteLine("Testing Option.Some(42)...");
            TestSome();
            Console.WriteLine("");
            Console.WriteLine("Testing Option.None()...");
            TestNone();
            Console.WriteLine("");
            Console.WriteLine("Testing Result.Ok(100)...");
            TestOk();
            Console.WriteLine("");
            Console.WriteLine("Testing Result.Err(error)...");
            TestErr();
        }

        private static void TestSome()
        {
            var opt = Opal.Runtime.Option.Some(42);
            Console.WriteLine("  Created Some(42)");
        }

        private static void TestNone()
        {
            var opt = Opal.Runtime.Option<int>.None();
            Console.WriteLine("  Created None");
        }

        private static void TestOk()
        {
            var result = Opal.Runtime.Result.Ok<int, string>(100);
            Console.WriteLine("  Created Ok(100)");
        }

        private static void TestErr()
        {
            var result = Opal.Runtime.Result.Err<object, string>("Something went wrong");
            Console.WriteLine("  Created Err(Something went wrong)");
        }

    }
}
