using System.Reflection;
using Calor.RoundTrip.Harness;
using Xunit;

namespace Calor.RoundTrip.Harness.Tests;

public class PostProcessTests
{
    // Access the private static method via reflection for testing
    private static string PostProcess(string emitted, string original)
    {
        var method = typeof(RoundTripPipeline).GetMethod(
            "PostProcessEmittedCSharp",
            BindingFlags.NonPublic | BindingFlags.Static);
        Assert.NotNull(method);
        return (string)method!.Invoke(null, [emitted, original])!;
    }

    [Fact]
    public void StripsCalorRuntimeUsing()
    {
        var emitted = "using System;\nusing Calor.Runtime;\nusing System.Linq;\n\nnamespace Foo { }";
        var original = "using System;\n\nnamespace Foo { }";

        var result = PostProcess(emitted, original);

        Assert.DoesNotContain("Calor.Runtime", result);
        Assert.Contains("using System;", result);
        Assert.Contains("using System.Linq;", result);
    }

    [Fact]
    public void StripsNullableEnable_WhenOriginalLacksIt()
    {
        var emitted = "#nullable enable\nusing System;\n\nnamespace Foo { }";
        var original = "using System;\n\nnamespace Foo { }";

        var result = PostProcess(emitted, original);

        Assert.DoesNotContain("#nullable enable", result);
    }

    [Fact]
    public void PreservesNullableEnable_WhenOriginalHasIt()
    {
        var emitted = "#nullable enable\nusing System;\n\nnamespace Foo { }";
        var original = "#nullable enable\nusing System;\n\nnamespace Foo { }";

        var result = PostProcess(emitted, original);

        Assert.Contains("#nullable enable", result);
    }

    [Fact]
    public void StripsAutoGeneratedHeaders()
    {
        var emitted = "// <auto-generated/>\nusing System;\n\nnamespace Foo { }";
        var original = "using System;\n\nnamespace Foo { }";

        var result = PostProcess(emitted, original);

        Assert.DoesNotContain("auto-generated", result);
        Assert.Contains("using System;", result);
    }

    [Fact]
    public void RemovesLeadingBlankLines()
    {
        var emitted = "\n\n\nusing System;\n\nnamespace Foo { }";
        var original = "using System;\n\nnamespace Foo { }";

        var result = PostProcess(emitted, original);

        Assert.StartsWith("using System;", result);
    }
}
