// <auto-generated>
// This code was generated by the OPAL compiler.
// Do not modify this file directly.
// </auto-generated>

using System;

namespace Hello
{
    public static class HelloModule
    {
        public static void Main()
        {
            Console.WriteLine("Hello from OPAL!");
        }

    }
}
