// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

#nullable enable

using System;
using Calor.Runtime;
using System.Collections.Generic;
using System.Linq;

namespace SkillSyntax
{
    public static class SkillSyntaxModule
    {
        public static void Main()
        {
            Console.WriteLine("=== Calor Skill Syntax Validation ===");
            Console.WriteLine("");
            TestArithmetic();
            TestComparison();
            TestControlFlow();
        }

        private static void TestArithmetic()
        {
            Console.WriteLine("Testing arithmetic operators...");
        }

        public static int Add(int a, int b)
        {
            return (a + b);
        }

        public static int Subtract(int a, int b)
        {
            return (a - b);
        }

        public static int Multiply(int a, int b)
        {
            return (a * b);
        }

        private static void TestComparison()
        {
            Console.WriteLine("Testing comparison operators...");
        }

        public static bool IsPositive(int x)
        {
            return (x > 0);
        }

        public static bool IsZero(int x)
        {
            return (x == 0);
        }

        private static void TestControlFlow()
        {
            Console.WriteLine("Testing control flow...");
            for (var i = 1; i <= 5; i++)
            {
                Console.WriteLine(i);
            }

        }

    }
}
