// <auto-generated>
// This code was generated by the Calor compiler.
// Do not modify this file directly.
// </auto-generated>

using System;
using Calor.Runtime;

namespace PatternMatchingDemo
{
    public static class PatternMatchingDemoModule
    {
        public static void Main()
        {
            var score = 85;
            var grade = score switch { >= 90 => "A", >= 80 => "B", >= 70 => "C", >= 60 => "D", _ => "F" };
            Console.WriteLine(("Grade: " + grade));
            var statusCode = 404;
            var status = statusCode switch { 200 => "OK", 201 => "Created", 400 => "Bad Request", 404 => "Not Found", 500 => "Server Error", _ => "Unknown Status" };
            Console.WriteLine(("HTTP Status: " + status));
            var value = -5;
            var desc = value switch { var n when (n > 100) => "large positive", var n when (n > 0) => "small positive", 0 => "zero", var n when (n > -100) => "small negative", _ => "large negative" };
            Console.WriteLine(("Description: " + desc));
            var dayNum = 3;
            var day = dayNum switch { 0 => "Sunday", 1 => "Monday", 2 => "Tuesday", 3 => "Wednesday", 4 => "Thursday", 5 => "Friday", 6 => "Saturday", _ => "Invalid day" };
            Console.WriteLine(("Day: " + day));
            var temp = 25;
            var tempDesc = temp switch { < 0 => "freezing", < 10 => "cold", < 20 => "cool", < 30 => "warm", < 40 => "hot", _ => "extreme" };
            Console.WriteLine(("Temperature: " + tempDesc));
        }

    }
}
